# Generated by Django 3.0.8 on 2020-10-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201006_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user_id',
            new_name='user',
        ),
    ]
